# Generated by Django 4.0.2 on 2022-08-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTodo', '0002_alter_todo_priority_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default=3, max_length=50),
        ),
    ]
